package sircow.preservedblizzard.mixin;

import it.unimi.dsi.fastutil.objects.Object2FloatMap;
import it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.ComposterBlock;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Mixin(ComposterBlock.class)
public class CompostorBlockMixin {
    @Shadow public static final Object2FloatMap<ItemLike> COMPOSTABLES = new Object2FloatOpenHashMap<>();
    @Inject(method = "bootStrap", at = @At("HEAD"), cancellable = true)
    private static void newValues(CallbackInfo ci) {
        COMPOSTABLES.defaultReturnValue(-1.0F);
        add(0.05F, Items.ACACIA_LEAVES);
        add(0.05F, Items.ALLIUM);
        add(0.05F, Items.AZALEA);
        add(0.05F, Items.AZALEA_LEAVES);
        add(0.05F, Items.AZURE_BLUET);
        add(0.05F, Items.BEETROOT);
        add(0.05F, Items.BEETROOT_SEEDS);
        add(0.05F, Items.BIRCH_LEAVES);
        add(0.05F, Items.BLUE_ORCHID);
        add(0.05F, Items.BROWN_MUSHROOM);
        add(0.05F, Items.CACTUS);
        add(0.05F, Items.CACTUS_FLOWER);
        add(0.05F, Items.CARROT);
        add(0.05F, Items.CARVED_PUMPKIN);
        add(0.05F, Items.CHERRY_LEAVES);
        add(0.05F, Items.CLOSED_EYEBLOSSOM);
        add(0.05F, Items.COCOA_BEANS);
        add(0.05F, Items.CORNFLOWER);
        add(0.05F, Items.CRIMSON_FUNGUS);
        add(0.05F, Items.CRIMSON_ROOTS);
        add(0.05F, Items.DANDELION);
        add(0.05F, Items.DARK_OAK_LEAVES);
        add(0.05F, Items.DRY_SHORT_GRASS);
        add(0.05F, Items.DRY_TALL_GRASS);
        add(0.05F, Items.FERN);
        add(0.05F, Items.FLOWERING_AZALEA);
        add(0.05F, Items.FLOWERING_AZALEA_LEAVES);
        add(0.05F, Items.GLOW_BERRIES);
        add(0.05F, Items.GLOW_LICHEN);
        add(0.05F, Items.JUNGLE_LEAVES);
        add(0.05F, Items.KELP);
        add(0.05F, Items.LARGE_FERN);
        add(0.05F, Items.LEAF_LITTER);
        add(0.05F, Items.LILAC);
        add(0.05F, Items.LILY_OF_THE_VALLEY);
        add(0.05F, Items.MANGROVE_LEAVES);
        add(0.05F, Items.MELON_SEEDS);
        add(0.05F, Items.MELON_SLICE);
        add(0.05F, Items.MOSS_BLOCK);
        add(0.05F, Items.MOSS_CARPET);
        add(0.05F, Items.NETHER_SPROUTS);
        add(0.05F, Items.NETHER_WART);
        add(0.05F, Items.OAK_LEAVES);
        add(0.05F, Items.OPEN_EYEBLOSSOM);
        add(0.05F, Items.ORANGE_TULIP);
        add(0.05F, Items.OXEYE_DAISY);
        add(0.05F, Items.PALE_HANGING_MOSS);
        add(0.05F, Items.PALE_MOSS_BLOCK);
        add(0.05F, Items.PALE_MOSS_CARPET);
        add(0.05F, Items.PALE_OAK_LEAVES);
        add(0.05F, Items.PEONY);
        add(0.05F, Items.PINK_PETALS);
        add(0.05F, Items.PINK_TULIP);
        add(0.05F, Items.POPPY);
        add(0.05F, Items.POTATO);
        add(0.05F, Items.PUMPKIN);
        add(0.05F, Items.PUMPKIN_SEEDS);
        add(0.05F, Items.RED_MUSHROOM);
        add(0.05F, Items.RED_TULIP);
        add(0.05F, Items.ROSE_BUSH);
        add(0.05F, Items.SEAGRASS);
        add(0.05F, Items.SHORT_GRASS);
        add(0.05F, Items.SMALL_DRIPLEAF);
        add(0.05F, Items.SPRUCE_LEAVES);
        add(0.05F, Items.SUGAR_CANE);
        add(0.05F, Items.SUNFLOWER);
        add(0.05F, Items.SWEET_BERRIES);
        add(0.05F, Items.TALL_GRASS);
        add(0.05F, Items.TWISTING_VINES);
        add(0.05F, Items.VINE);
        add(0.05F, Items.WARPED_FUNGUS);
        add(0.05F, Items.WARPED_ROOTS);
        add(0.05F, Items.WEEPING_VINES);
        add(0.05F, Items.WHEAT);
        add(0.05F, Items.WHEAT_SEEDS);
        add(0.05F, Items.WHITE_TULIP);
        add(0.05F, Items.WILDFLOWERS);
        add(0.1F, Items.BIG_DRIPLEAF);
        add(0.1F, Items.BIRCH_SAPLING);
        add(0.1F, Items.BROWN_MUSHROOM_BLOCK);
        add(0.1F, Items.BUSH);
        add(0.1F, Items.CHERRY_SAPLING);
        add(0.1F, Items.DARK_OAK_SAPLING);
        add(0.1F, Items.DRIED_KELP);
        add(0.1F, Items.FIREFLY_BUSH);
        add(0.1F, Items.HANGING_ROOTS);
        add(0.1F, Items.JUNGLE_SAPLING);
        add(0.1F, Items.LILY_PAD);
        add(0.1F, Items.MANGROVE_PROPAGULE);
        add(0.1F, Items.NETHER_WART_BLOCK);
        add(0.1F, Items.OAK_SAPLING);
        add(0.1F, Items.PALE_OAK_SAPLING);
        add(0.1F, Items.RED_MUSHROOM_BLOCK);
        add(0.1F, Items.SEA_PICKLE);
        add(0.1F, Items.SPRUCE_SAPLING);
        add(0.1F, Items.WARPED_WART_BLOCK);
        add(0.25F, Items.APPLE);
        add(0.25F, Items.BAKED_POTATO);
        add(0.25F, Items.BREAD);
        add(0.25F, Items.COOKIE);
        add(0.25F, Items.MANGROVE_ROOTS);
        add(0.25F, Items.MELON);
        add(0.25F, Items.MUSHROOM_STEM);
        add(0.25F, Items.WITHER_ROSE);
        add(0.5F, Items.DRIED_KELP_BLOCK);
        add(0.5F, Items.HAY_BLOCK);
        add(0.5F, Items.PITCHER_POD);
        add(0.5F, Items.SHROOMLIGHT);
        add(0.5F, Items.SPORE_BLOSSOM);
        add(0.5F, Items.TORCHFLOWER_SEEDS);
        add(1.0F, Items.CAKE);
        add(1.0F, Items.PITCHER_PLANT);
        add(1.0F, Items.PUMPKIN_PIE);
        add(1.0F, Items.TORCHFLOWER);
        ci.cancel();
    }

    @Unique
    private static void add(float chance, ItemLike item) {
        COMPOSTABLES.put(item.asItem(), chance);
    }
}
